# Generated by Django 4.2.3 on 2023-07-07 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('titulo', models.CharField(max_length=100)),
                ('descrição', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('ANALISES', 'Análises'), ('PROGRAMACAO', 'Programação'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=15)),
                ('vizualizacoes', models.IntegerField(default=0)),
                ('data_criação', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
