# Generated by Django 4.2.3 on 2023-07-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fime',
            new_name='Filme',
        ),
    ]
