# Generated by Django 4.2.2 on 2023-07-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_rename_fime_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
